In [3]:
!pip install emoji

Collecting emoji
  Obtaining dependency information for emoji from https://files.pythonhosted.org/packages/91/db/a0335710caaa6d0aebdaa65ad4df789c15d89b7babd9a30277838a7d9aac/emoji-2.14.1-py3-none-any.whl.metadata
  Downloading emoji-2.14.1-py3-none-any.whl.metadata (5.7 kB)
Downloading emoji-2.14.1-py3-none-any.whl (590 kB)
   ---------------------------------------- 0.0/590.6 kB ? eta -:--:--
   -- ------------------------------------ 41.0/590.6 kB 991.0 kB/s eta 0:00:01
   ------- -------------------------------- 112.6/590.6 kB 1.3 MB/s eta 0:00:01
   --------------- ------------------------ 225.3/590.6 kB 1.7 MB/s eta 0:00:01
   ---------------------- ----------------- 327.7/590.6 kB 1.8 MB/s eta 0:00:01
   ----------------------------- ---------- 440.3/590.6 kB 2.0 MB/s eta 0:00:01
   ----------------------------------- ---- 522.2/590.6 kB 1.9 MB/s eta 0:00:01
   -------------------------------------- - 563.2/590.6 kB 1.8 MB/s eta 0:00:01
   ---------------------------------------- 590.6/590.6 kB 1.7 MB/s eta 0:00:00
Installing collected packages: emoji
Successfully installed emoji-2.14.1

In [19]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import emoji
import re

In [9]:
twitter_validation = pd.read_csv('twitter_validation.csv',header = None)
twitter_validation

,0,1,2,3
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [11]:
twitter_validation.columns = ['Tweer_ID','Entity','Sentiment','Tweet_Content']
twitter_validation

,Tweer_ID,Entity,Sentiment,Tweet_Content
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,⭐️ Toronto is the arts and culture capital of ...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [12]:
twitter_validation.isnull().sum()

Tweer_ID         0
Entity           0
Sentiment        0
Tweet_Content    0
dtype: int64

In [15]:
twitter_validation.duplicated().sum()

0

In [16]:
twitter_validation.dtypes

Tweer_ID          int64
Entity           object
Sentiment        object
Tweet_Content    object
dtype: object

In [17]:
# Emoji removal function
def remove_emojis(text):
    return emoji.replace_emoji(text, replace='')

In [18]:
# Apply to a specific column
twitter_validation['Tweet_Content'] = twitter_validation['Tweet_Content'].apply(remove_emojis)
twitter_validation

,Tweer_ID,Entity,Sentiment,Tweet_Content
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,@Microsoft Why do I pay for WORD when it funct...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,Toronto is the arts and culture capital of Ca...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so it’s time to drink wine n play...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson & Johnson to stop selling talc baby po...

In [20]:
# to remove @ and related signs
def clean_text (text):
    text = re.sub(r'[^a-zA-Z0-9 .,!?\'\"-]', '', text)
    return text

In [21]:
# Apply to a specific column
twitter_validation['Tweet_Content'] = twitter_validation['Tweet_Content'].apply(clean_text)
twitter_validation

,Tweer_ID,Entity,Sentiment,Tweet_Content
0,3364,Facebook,Irrelevant,I mentioned on Facebook that I was struggling ...
1,352,Amazon,Neutral,BBC News - Amazon boss Jeff Bezos rejects clai...
2,8312,Microsoft,Negative,Microsoft Why do I pay for WORD when it functi...
3,4371,CS-GO,Negative,"CSGO matchmaking is so full of closet hacking,..."
4,4433,Google,Neutral,Now the President is slapping Americans in the...
...,...,...,...,...
995,4891,GrandTheftAuto(GTA),Irrelevant,Toronto is the arts and culture capital of Ca...
996,4359,CS-GO,Irrelevant,tHIS IS ACTUALLY A GOOD MOVE TOT BRING MORE VI...
997,2652,Borderlands,Positive,Today sucked so its time to drink wine n play ...
998,8069,Microsoft,Positive,Bought a fraction of Microsoft today. Small wins.
999,6960,johnson&johnson,Neutral,Johnson Johnson to stop selling talc baby pow...

In [23]:
 twitter_validation.to_csv('cleaned_twitter_validation.csv')